# Biomass

<br><br>

## 1. Load packages

```{r, message=FALSE, warning=FALSE}
require(ggplot2)
require(dplyr)
require(nlme)
require(viridis)
require(reshape2)
require(car)
require(tidyverse)
require(broom)
require(egg)
```

<br>

## 2. Load data	and rearrange

```{r}
# define paths
data.dir   = "/Users/consti/Desktop/PhD/Publication_material/10_PhenogrowthEx3/Rdata/Experiment"
output.dir = "/Users/consti/Desktop/PhD/Publication_material/10_PhenogrowthEx3/Routput"

#load data
data       = read.table(paste(data.dir,"biomass.csv",sep="/"), header=T, sep=",")

#delete species epithet
data$Species = gsub(' [A-z ]*', '' , data$Species)

#get root-mass fraction
data$RSR = data$Root/data$Shoot

#sample sizes
table(data$Treatment, data$Species)

#Melt data to a long format
data       = melt(data, id = c("Species", "ID", "Treatment"), 
                  variable.name="organ", value.name="biomass")

#Ordering of factors
Treatments     = c("control", "autumn", "autumn-spring", "spring") #order treatments
data$Treatment = factor(data$Treatment, levels=Treatments, ordered=T)
Species        = c("Quercus", "Fagus", "Lonicera") #order species
data$Species   = factor(data$Species, levels=Species, ordered=T)
variable       = c("Total", "Shoot", "Root", "RSR") #order organ
data$organ     = factor(data$organ, levels=variable, ordered=T)

#define plot theme
plotTheme = theme(legend.position   = "right",
                  legend.background = element_rect(fill=NA, size=0.5, linetype="solid"),
                  legend.text       = element_text(color="black"),
                  panel.grid.major  = element_blank(),
                  panel.grid.minor  = element_blank(),
                  panel.background  = element_rect(colour = NA, size=1, fill="grey97"),
                  axis.text.x       = element_text(angle = 45, hjust = 1),
                  axis.line.y       = element_line(color = "black"),
                  strip.background  = element_rect(fill=NA),
                  strip.text        = element_text(colour = 'black'))
```

<br>

## 3. Check total and per treatment biomass distribution 

```{r}
#Species-level plot
ggplot(data = data, mapping = aes(biomass, fill=organ)) +
  geom_histogram(bins=10, position="identity", color="black") +
  xlab("Biomass (g) [panels 1-3]                     
                                                                                           Biomass ratio [panel 4]") +
  ylab("Count") +
  scale_fill_viridis(option="E",discrete=TRUE) +
  facet_grid(Species~organ, scales="free") + 
  plotTheme

#Treatment-level plot
ggplot(data = data[data$organ %in% c("Shoot","Root"),], mapping = aes(biomass, fill=organ)) +
  geom_histogram(bins=10, color="black") +
  xlab("Biomass (g)") +
  ylab("Count") +
  scale_fill_viridis(option="C",discrete=TRUE) +
  facet_grid(organ+Species~Treatment, scales="free") + 
  plotTheme
```

<br>

## 4. Treatment analysis

```{r, results="hide"}
#######
# ANOVA
#######

#Extract model info and check ANOVA assumptions
resultsLM = data %>% 
    group_by(Species,organ) %>% 
    do({model = aov(biomass ~ Treatment, data=.)        # create your model
    data.frame(tidy(model)[1,],                         # get coefficient info
               glance(model)[1,],                       # get model info
               leveneTest=tidy(leveneTest(model))[1,4], # check Homogeneity of variances
               tidy(shapiro.test(x = residuals(object = model)))[1,2] # check for Normality
               )}) %>%           
    #select(Species, organ, p.value, r.squared, adj.r.squared, p.value.2, p.value.3) %>% #delete columns
    rename(leveneTest=p.value.2, shapiroTest=p.value.3) %>%                             #rename columns
    mutate(sig = ifelse(p.value<0.05, "**", ifelse(p.value<0.1, "*", "")),
           Treatment="control")     #add significance and dummy column for plotting
data_frame(resultsLM)

# Plots to check ANOVA assumptions
data$category = paste(data$Species,data$organ, sep="_") #create identifier column
category.list = as.factor(unique(data$category))        #create category vector
par(mfrow=c(2,2))                                       #set plot layout
for (category in category.list){                        #loop over categories
  tab.subset=data[data$category==category, ]            #create table subset
  plot(aov(biomass ~ Treatment, data=tab.subset), 1, main=category) # 1. Homogeneity of variances
  plot(aov(biomass ~ Treatment, data=tab.subset), 2, main=category) # 2. Normality
}


#####
#Plot
#####

Boxp <- ggplot(data = data, mapping = aes(x = Treatment, y = biomass, fill=Treatment)) +
  geom_boxplot(position=position_dodge(0.8),coef=1e30) +
  geom_text(data = resultsLM,
            mapping = aes(x = Inf, y = Inf, hjust = 2, vjust = 2, 
                            label = paste("R2 = ", round(r.squared,2), sig, sep="")), 
              size=3.5, color="black")+
  xlab("Treatment") +
  ylab("Biomass (g)") +
  scale_fill_viridis(option="E",discrete=TRUE) +
  facet_grid(organ~Species, scales="free") + 
  plotTheme
Boxp


#########
#Save PDF
#########

pdf(paste(output.dir,"Biomass.pdf",sep="/"), width=7, height=7, useDingbats=FALSE)
Boxp
dev.off()
```

<br>

## 5. Relative biomass analysis

```{r, message=FALSE, warning=FALSE}
###########################
# Multivariate linear model
###########################


#Create spring and autumn treatments
####################################

data$spring = ifelse(data$Treatment %in% c("control","autumn"), "no","warming")
data$autumn = ifelse(data$Treatment %in% c("control","spring"), "no","warming")


#Transform biomass to percentage anomaly
########################################

#get means per species
data1 = data %>% 
    group_by(Species,organ) %>% 
    summarize(Mean = mean(biomass, na.rm=TRUE))
#merge data
data1 <-merge(data, data1, all.x=T, by=c("Species","organ"))
#get precentage change in biomass
data1$relativeBiomass = (data1$biomass / data1$Mean -1) * 100


#Multivariate linear model
##########################

resultsLM = data1 %>% 
    group_by(Species,organ) %>% 
    do({model = lm(relativeBiomass ~ spring*autumn, data=.)  # create your model
    data.frame(tidy(model))}) %>%           # get coefficient info
    filter(!term %in% c("(Intercept)")) %>% # delete rows
    dplyr::select(Species, organ, term, p.value, estimate, std.error) %>% #delete columns
    mutate_if(is.numeric, round, 2) %>%   
    mutate(sig = ifelse(p.value<0.05, "**", ifelse(p.value<=0.1, "*", ""))) #add significance
data.frame(resultsLM)

#Plot
#####

#Ordering of factors
term           = c("springwarming", "autumnwarming", "springwarming:autumnwarming") #order treatments
resultsLM$term = factor(resultsLM$term, levels=term, ordered=T)
#create panel labels
dat_text       = data.frame(
  label        = c("a","b","c","d","e","f","g","h","i","j","k","l"),
  organ        = rep(c("Total","Shoot","Root","RSR"),3),
  Species      = c(rep("Quercus",4), rep("Fagus",4), rep("Lonicera",4)),
  term         = "springwarming")
#Plot
LMplot = ggplot(data = resultsLM, mapping = aes(x = term, y = estimate, 
                                                fill=organ, alpha=term)) +
  geom_bar(position=position_dodge(), stat="identity", color="black") +
    geom_errorbar(aes(ymin=estimate-std.error, ymax=estimate+std.error),
                  width=.2,                    # Width of the error bars
                  position=position_dodge(.9))+
  geom_hline(yintercept=0) +
  geom_text(data = dat_text, mapping = aes(x = -Inf, y = -Inf, 
                                           hjust = -0.1, vjust = -1,
                                           label = paste("(",label,")",sep=""),
                                           fontface = "bold"))+
  stat_summary(geom = 'text', label = resultsLM$sig, 
               fun.y = mean, vjust = 2) +
  scale_color_viridis(option="viridis",discrete=TRUE) +
  scale_alpha_discrete(range = c(1, 0.7)) +
  xlab("Phenophase") +
  ylab("Effect size (%)") +
  scale_fill_viridis(option="E",discrete=TRUE) +
  facet_grid(Species~organ) + 
  plotTheme
LMplot

########
# T-test
########

#get means of control group
###########################

data1 = data %>% 
    filter(Treatment %in% c("control")) %>%
    group_by(Species,organ) %>% 
    summarize(Mean = mean(biomass, na.rm=TRUE))
#merge data
data1 <-merge(data[!data$Treatment=="control",], data1, all.x=T, by=c("Species","organ"))
#get precentage change in biomass
data1$relativeBiomass = ifelse(data1$organ!="RSR", (data1$biomass / data1$Mean -1) * 100,
                               (data1$biomass - data1$Mean)*100)
#Ordering of factors
Treatments     = c("spring", "autumn", "autumn-spring") #order treatments
data1$Treatment = factor(data1$Treatment, levels=Treatments, ordered=T)
Species     = c("Quercus", "Fagus", "Lonicera") #order treatments
data1$Species = factor(data1$Species, levels=Species, ordered=T)

#T-test
#######

resultsTT = data1 %>% 
    group_by(Species,organ,Treatment) %>% 
    do({model = t.test(.$relativeBiomass)        # create your model
    data.frame(tidy(model),
               tidy(shapiro.test(x = .$relativeBiomass))[1,2])}) %>%           
    select(Species, organ, Treatment, p.value, estimate, p.value.1) %>% #delete columns
    rename(shapiroTest=p.value.1) %>%   
    mutate_if(is.numeric, round, 2) %>%   
    mutate(sig = ifelse(p.value<0.05, "**", ifelse(p.value<=0.1, "*", ""))) #add significance
#order statistics table to match dataframe
resultsTT = resultsTT[with(resultsTT, order(resultsTT$Species, resultsTT$organ)), ]
data.frame(resultsTT)

#Plot
#####

#create panel labels
dat_text <- data.frame(
  label = c("a","b","c","d","e","f","g","h","i","j","k","l"),
  organ   = rep(c("Total","Shoot","Root","RSR"),3),
  Species     = c(rep("Quercus",4), rep("Fagus",4), rep("Lonicera",4)),
  Treatment   = "spring")
#Plot
BiomassChangePlot = ggplot(data = data1, mapping = aes(x = Treatment, y = relativeBiomass, 
                                                       fill=organ, alpha=Treatment)) +
  stat_summary(fun.y = mean, 
                 geom = "bar", color="black") + 
  stat_summary(fun.data = mean_se,  
                 geom = "errorbar", width=0.2) + 
  geom_hline(yintercept=0) +
  geom_text(data = dat_text, mapping = aes(x = -Inf, y = -Inf, 
                                           hjust = -0.1, vjust = -1,
                                           label = paste("(",label,")",sep=""),
                                           fontface = "bold"))+
  stat_summary(geom = 'text', label = resultsTT$sig, 
               fun.y = max, vjust = 2.9) +
  scale_alpha_discrete(range = c(1, 0.7)) +
  coord_cartesian(ylim = c(-60, 60))+
  xlab("Treatment") +
  ylab("Biomass change (%)") +
  scale_fill_viridis(option="E",discrete=TRUE) +
  facet_grid(Species~organ) + 
  plotTheme
BiomassChangePlot

#########
#Save PDF
#########

pdf(paste(output.dir,"BiomassLinearTreatmentModel.pdf",sep="/"), width=8, height=7, useDingbats=FALSE)
LMplot
dev.off()

pdf(paste(output.dir,"BiomassChange.pdf",sep="/"), width=8, height=7, useDingbats=FALSE)
BiomassChangePlot
dev.off()
```

